  # Omakase Ruby styling for Rails
  inherit_gem:
    rubocop-rails-omakase: rubocop.yml

  require:
    - rubocop-rails

  AllCops:
    TargetRubyVersion: 3.0
    Exclude:
      - "db/schema.rb"
      - "bin/*"
      - "node_modules/**/*"
      - "config/**/*"
      - "vendor/**/*"

  Layout/LineLength:
    Max: 200

  Rails:
    Enabled: true
